NOT_NEED_SEARCH = {
    "小偷Litten(測試題)",
    "[2017AF-B]刀槍不入、神功護體",
    "[2017AF-B]即刻救援",
    "[2017AF-B]轉動的數字不生苔",
    "[2017AF-Bonus]蜂巢是完美的建築",
    "[2017AF-E]宇宙立方",
    "[2017AF-E]數出必有因",
    "[2017AF-E]解開一個100位的質數問題要算到世界末日",
    "[2017AM-F]中華民國萬萬稅",
    "[2018AM]有一種檸檬，叫做蕚羊的檸檬",
    "[2018AM]有一種選舉叫做智力測驗",
    "[2018AM]滾滾曾文溪都是水，浪花淘盡憂銹青年",
    "[2019-投稿-A]兒時記趣",
    "[2019-投稿-A]剪刀石頭布",
    "[2019AM-A] 最簡單問題??",
    "[2019AM-A] 皇后",
    "[2019AM-A] 關係運算子",
    "[2019AM-B] 一中半島爭奪戰",
    "[2019AM-B] 超級盃計分",
    "[2019AM-Bonus] Peter's Smokes",
    "[2019AM-Bonus] Soda Surpler",
    "[2019AM-C] 保險箱開鎖任務",
    "[2019AM-C] 尋找尼斯湖水怪",
    "[2019AM-C] 戰鬥睡眠",
    "[2019AM-D] 化簡分數",
    "[2019AM-E] 神奇遙控器",
    "[2019BF-A]打羽毛球囉～～～～",
    "[2020-投稿-A]你被當，我們扛",
    "[2020-投稿-F] My loves, Win10",
    "[2021上][期末][while]最大小費數",
    "[2021上][期末][while]最大小費數",
    "[2021上][期末][while]最小質序",
    "[B5]每日幸運星",
    "[for] 小蘿莉的數學家教A",
    "[for] 小蘿莉的數學家教B",
    "[for] 小蘿莉的數學家教C",
    "[for] 敗家的理由",
    "[for] 當一個便當吃不飽時.你可以吃兩個",
    "[for] 誰能想的到，這名16歲少女，在四年前，只是一名12歲的小丫頭",
    "[if⁄else]BetaCome",
    "[if⁄else]棒打老虎雞吃蟲",
    "[loop] 數字的好朋友",
    "[loop] 數字的好朋友",
    "[Python-3][loop][string]態度決定分數 ",
    "[Python-3][loop][type][error]態度的重要性",
    "[Python-3][loop][type]失敗的分組",
    "[Python-3][loop]天外奇雞 ",
    "[Python-3][loop]管你三七二十一 ",
    "[Python-3][nested loop]nn乘法表",
    "[Python-3][nested loop]好餓好餓的毛毛蟲",
    "[Python][2021上][期中][Conditional]A. 換電腦啦",
    "[Python][2021上][期中][Conditional]A. 棄保效應",
    "[Python][2021上][期中][Conditional]B. 投標須知 ",
    "[Python][2021上][期中][if][loop] 賽亞人的驕傲",
    "[Python][2021上][期中][if][string]E. TnfshTag",
    "[Python][2021上][期中][if][string]E. TnfshTag",
    "[Python][2021上][期中][if][string]E. You can run, but you can’t hide",
    "[Python][2021上][期中][if][string]E. You can run, but you can’t hide",
    "[Python][2021上][期中][loop][list]C. 班聯會主席",
    "[Python][2021上][期中][loop][list]C. 難中劵",
    "[Python][2021上][期中][loop][list]D. Percentile Rank",
    "[Python][2021上][期中][loop][list]D. Z-transform ",
    "[Python][2021上][期中][loop][string]B. 稿費好難賺 ",
    "[Python][2021上][期中][投稿][loop][if][string]Bonus3. 互補團隊 ",
    "[Python][2021上][期中][投稿][loop][if][string]Bonus3. 互補團隊 ",
    "[Python][2021上][期末][data]2024大選開票",
    "[Python][2021上][期末][data]你同意我不同意之公投開票",
    "[Python][2021上][期末][if][loop] 數字的壞朋友",
    "[Python][2021上][期末][if][loop] 數字的壞朋友",
    "[Python][2021上][期末][loop]希爾伯特矩陣",
    "[Python][2022上][期中][if]某年某月的某一天",
    "[while] 運氣爆棚的小英",
    "[while]狼一中集團尾牙大放送",
    "[while]討厭的規律數列",
    "[二維陣列] 卷積神經網路-平均池化",
    "[二維陣列] 卷積神經網路-最大池化",
    "[投稿][python][loop]小明發大財",
    "[投稿][python][nested loop][if]吉哥的微吉分",
    "[投稿][python][nested loop][if]幾A幾B",
    "[條件判斷] 超級刮刮樂",
    "[變數與運算子] 乘法反元素",
    "[變數與運算子] 分組",
    "[變數與運算子] 菜園的面積",
    "[迴圈] 三的倍數",
    "[迴圈] 積沙成塔",
    "[迴圈] 號碼產生機",
    "[迴圈] 質數的判斷",
    "[迴圈] 馬克杯",
    "ASCII decode",
    "Brute-force attack Caesar cipher",
    "Decrypt the cipher** 　#Python #dict",
    "Morse code encode",
    # "pD",
    # "pE",
    "Shopaholic",
    "Sim-Scoreboard**** 　#Python #list.sort #多條件排序",
    "Sum of power digit",
    "伸縮乘法表",
    "修復字串",
    "又見沙漏* 　#Python #雙層for迴圈",
    "地毯編織",
    "快樂天堂",
    "成績等第判別* 　#Python15 #判斷結構",
    "日期強迫症* 　#Python4 #str分割",
    "根號排列",
    "水仙花數** 　＃Python13 #巢狀迴圈 #str資料結構",
    "畢氏三元數",
    "神文* 　#Python30 #string",
    "老二哲學",
    "華氏溫度轉攝氏溫度* 　#Python #輸入輸出",
    "高中運動會** 　#Python #巢狀迴圈 #GCD",
}
